apiVersion: v1
kind: Service
metadata:  
  name: db
spec:
  selector:    
    app: mysql
  type: NodePort
  ports:  
  - name: mysql
    port: 3306
    nodePort: 30718
    protocol: TCP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7.16
        resources:
          requests:
            memory: "350Mi"
            cpu: "0.2"
          limits:
            memory: "350Mi"
            cpu: "0.2"
        name: mysql
        args: 
          - --character-set-server=utf8
          - --collation-server=utf8_general_ci
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: farzad_yasaman
        - name: MYSQL_DATABASE
          value: joboonja
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
          subPath: farzad-mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim